// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Bh9qYhBqryFUVhTvGw5rcYw38mbkkq0',
    appId: '1:553239732400:web:658ab30744161bfb385b75',
    messagingSenderId: '553239732400',
    projectId: 'hiresense-a1827',
    authDomain: 'hiresense-a1827.firebaseapp.com',
    storageBucket: 'hiresense-a1827.firebasestorage.app',
    measurementId: 'G-ZNS7ST7EF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATegJJSXHLw2H47BRDa2Mg01uqXrerTG0',
    appId: '1:553239732400:android:3cd07971fbcbdf1a385b75',
    messagingSenderId: '553239732400',
    projectId: 'hiresense-a1827',
    storageBucket: 'hiresense-a1827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGL49qvRILmll5AOz21cPaFKarwR3TZJQ',
    appId: '1:553239732400:ios:6256b6d88afa3888385b75',
    messagingSenderId: '553239732400',
    projectId: 'hiresense-a1827',
    storageBucket: 'hiresense-a1827.firebasestorage.app',
    androidClientId: '553239732400-d6n4mnisn0d0qpiopctrf23hr004uvmk.apps.googleusercontent.com',
    iosClientId: '553239732400-chbijqs749g60ac00nnh7teprv5pup1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiresense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGL49qvRILmll5AOz21cPaFKarwR3TZJQ',
    appId: '1:553239732400:ios:6256b6d88afa3888385b75',
    messagingSenderId: '553239732400',
    projectId: 'hiresense-a1827',
    storageBucket: 'hiresense-a1827.firebasestorage.app',
    androidClientId: '553239732400-d6n4mnisn0d0qpiopctrf23hr004uvmk.apps.googleusercontent.com',
    iosClientId: '553239732400-chbijqs749g60ac00nnh7teprv5pup1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiresense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4Bh9qYhBqryFUVhTvGw5rcYw38mbkkq0',
    appId: '1:553239732400:web:81fdb8205b3ce742385b75',
    messagingSenderId: '553239732400',
    projectId: 'hiresense-a1827',
    authDomain: 'hiresense-a1827.firebaseapp.com',
    storageBucket: 'hiresense-a1827.firebasestorage.app',
    measurementId: 'G-CQ239DMX8N',
  );
}
